name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/brunozer0/projectschoolagenda:latest \
            -t ghcr.io/brunozer0/projectschoolagenda:${{ github.sha }} \
            .

      - name: Push Docker image (latest)
        run: |
          docker push ghcr.io/brunozer0/projectschoolagenda:latest

      - name: Push Docker image (sha)
        run: |
          docker push ghcr.io/brunozer0/projectschoolagenda:${{ github.sha }}